# Generated by Django 6.0.5 on 2026-05-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(help_text='Keyword or phrase to trigger the rule', max_length=255)),
                ('action', models.TextField(help_text='Response text or transformation template')),
                ('rule_type', models.CharField(choices=[('respond', 'Custom Response'), ('transform', 'Transform Input')], default='respond', max_length=20)),
                ('agent_key', models.CharField(blank=True, help_text='Optional: restrict to specific agent', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
