# Generated by Django 4.2.16 on 2026-07-14 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent_app', '0005_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='google/gemma-2-2b-it', max_length=255)),
                ('dataset_size', models.CharField(default='100k', max_length=10)),
                ('total_samples', models.IntegerField(default=100000)),
                ('batch_size', models.IntegerField(default=10000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_round', models.IntegerField(default=0)),
                ('total_rounds', models.IntegerField(default=10)),
                ('current_loss', models.FloatField(blank=True, null=True)),
                ('email', models.EmailField(help_text='Email for notifications', max_length=254)),
                ('notify_on_complete', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
