# Generated by Django 4.2.30 on 2026-07-31 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent_app', '0006_trainingjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('auto', 'Auto')], default='dark', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('auto', 'Auto')], default='en', max_length=10)),
                ('default_agent', models.CharField(default='chat', max_length=50)),
                ('show_timestamps', models.BooleanField(default=True)),
                ('send_on_enter', models.BooleanField(default=True)),
                ('font_size', models.IntegerField(default=14)),
                ('email_notifications', models.BooleanField(default=True)),
                ('training_notifications', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('default_model', models.CharField(default='google/gemma-2-2b-it', max_length=255)),
                ('default_dataset_size', models.CharField(default='100k', max_length=10)),
                ('default_epochs', models.IntegerField(default=3)),
                ('default_learning_rate', models.FloatField(default=0.0002)),
                ('openai_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('huggingface_token', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_user', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_pass', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
